r"""A mixture-of-functions task where expert specialization can be read off directly.

The prompt asks for a dataset in which specialization is *inspectable*, not merely inferred
from a metric. That requires the ground truth to exist: every token here is generated by one
of :math:`K` known functions, and the identity of that function is recorded. Whether a
router discovered the structure is then a question about a confusion matrix, not a matter of
interpretation.

Each token's features split into two parts with different jobs:

.. math::

    x = [\,u \mid v\,], \qquad
    z = \arg\max_k (W_{\text{sel}}^\top u)_k, \qquad
    y = \sin\!\big(\omega_z (a_z \cdot v) + \varphi_z\big)

The **selector** half :math:`u` determines *which* function applies; the **value** half
:math:`v` is what that function acts on. The split is deliberate. If one vector did both
jobs, a model could partly solve the task without routing — it could regress :math:`y` from
:math:`x` directly — and a failure to specialize would be indistinguishable from a task that
never needed specialization. Here the two are independent by construction, so a model that
ignores :math:`u` cannot do better than predicting the mean of :math:`K` unrelated
sinusoids.

The functions differ in frequency, direction, and phase, so no single smooth function fits
them all, and a dense network must spend capacity representing a mixture that a router could
have separated.
"""

from __future__ import annotations

from dataclasses import dataclass

import torch
from torch import Tensor


@dataclass(frozen=True, slots=True)
class MixtureTask:
    """Tokens drawn from a known mixture of functions.

    Attributes:
        inputs: Shape ``(n_sequences, seq_len, d_in)``.
        targets: Shape ``(n_sequences, seq_len, 1)``.
        latent: Shape ``(n_sequences, seq_len)`` index of the generating function. Ground
            truth for specialization; never shown to any model.
        n_functions: Number of generating functions.
    """

    inputs: Tensor
    targets: Tensor
    latent: Tensor
    n_functions: int

    def __post_init__(self) -> None:
        """Validate the task.

        Raises:
            ValueError: If the tensors disagree on shape.
        """

        if self.inputs.shape[:2] != self.latent.shape:
            raise ValueError("inputs and latent must agree on sequence and token counts")
        if self.targets.shape[:2] != self.latent.shape:
            raise ValueError("targets and latent must agree on sequence and token counts")

    @property
    def d_in(self) -> int:
        """Input width."""

        return int(self.inputs.shape[-1])

    def flat_latent(self) -> Tensor:
        """Return the latent ids flattened to one entry per token."""

        return self.latent.reshape(-1)


def generate(
    *,
    n_sequences: int,
    seq_len: int = 16,
    n_functions: int = 4,
    d_selector: int = 4,
    d_value: int = 4,
    seed: int = 0,
) -> MixtureTask:
    """Sample tokens from a mixture of sinusoidal functions.

    Args:
        n_sequences: Sequences to generate.
        seq_len: Tokens per sequence.
        n_functions: Number of generating functions.
        d_selector: Width of the half that decides which function applies.
        d_value: Width of the half the function acts on.
        seed: Seed for every draw, including the function bank.

    Returns:
        The task.

    Raises:
        ValueError: If any size is not positive, or fewer than two functions are requested.
    """

    if n_functions < 2:
        raise ValueError("n_functions must be at least 2")
    if min(n_sequences, seq_len, d_selector, d_value) <= 0:
        raise ValueError("sizes must be positive")

    generator = torch.Generator().manual_seed(seed)

    # The function bank. Fixed across the whole task so train and test share the same
    # mixture: this measures specialization, not extrapolation to unseen functions.
    selector_weights = torch.randn((d_selector, n_functions), generator=generator)
    directions = torch.randn((n_functions, d_value), generator=generator)
    directions = directions / directions.norm(dim=-1, keepdim=True)
    frequencies = 1.0 + 2.0 * torch.rand((n_functions,), generator=generator)
    phases = 2 * torch.pi * torch.rand((n_functions,), generator=generator)

    shape = (n_sequences, seq_len)
    selector = torch.randn((*shape, d_selector), generator=generator)
    value = torch.randn((*shape, d_value), generator=generator)

    latent = (selector @ selector_weights).argmax(dim=-1)
    projection = (value * directions[latent]).sum(dim=-1)
    targets = torch.sin(frequencies[latent] * projection + phases[latent]).unsqueeze(-1)

    return MixtureTask(
        inputs=torch.cat([selector, value], dim=-1),
        targets=targets,
        latent=latent,
        n_functions=n_functions,
    )


def specialization_matrix(
    latent: Tensor, expert: Tensor, n_functions: int, n_experts: int
) -> Tensor:
    """Count how often each generating function was routed to each expert.

    Args:
        latent: Shape ``(N,)`` true function ids.
        expert: Shape ``(N,)`` chosen expert per token.
        n_functions: Number of generating functions.
        n_experts: Number of experts.

    Returns:
        Shape ``(n_functions, n_experts)`` counts.
    """

    matrix = torch.zeros((n_functions, n_experts))
    for function_id, expert_id in zip(latent.tolist(), expert.tolist(), strict=True):
        matrix[int(function_id), int(expert_id)] += 1
    return matrix


def specialization_purity(matrix: Tensor) -> float:
    """Return the fraction of tokens whose expert is its function's dominant expert.

    This is a permutation-invariant summary: expert identities are arbitrary, so what
    matters is whether each function concentrates on *some* expert, not on a particular
    one. A value near ``1`` means the router recovered the mixture; a value near
    ``1 / n_functions`` means routing is unrelated to the generating structure.

    Note the asymmetry: this measures whether each function has a home, not whether each
    expert has one function. Two functions sharing a single expert score well here, which
    is why the report reads it beside the utilization spread rather than alone.

    Args:
        matrix: Shape ``(n_functions, n_experts)`` counts.

    Returns:
        Purity in ``[0, 1]``.
    """

    total = float(matrix.sum())
    if total == 0:
        return 0.0
    return float(matrix.max(dim=1).values.sum() / total)
